#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Before commit, Checking format, linting and typing your project.'

cd frontend

# Check Prettier standards
echo '🔎 Check formatting...'
npm run check-format ||
(
    echo '🤣🤣🤣🤣 Prettier Check Failed.🤣🤣🤣🤣
                Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
echo '🔎 Check linting...'
npm run check-lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check tsconfig standards
echo '🔎 Check typing...'
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'