#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GIT_DIFFS=$(git diff --cached --name-only | grep "frontend")

if [ -z GIT_DIFFS ]; then
  exit 0
fi

echo '🏛🏛🏛🏛... Before push, Trying to build now. 🏛🏛🏛🏛'

cd frontend

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

echo '✅✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'