export enum CATEGORY {
  MEAL = 'MEAL',
  STUDY = 'STUDY',
  ETC = 'ETC',
  COMPETITION = 'COMPETITION',
  PROJECT = 'PROJECT',
}

export enum LOCATION {
  ONLINE = 'ONLINE',
  SEOUL = 'SEOUL',
  INCHEON = 'INCHEON',
  BUSAN = 'BUSAN',
  DAEGU = 'DAEGU',
  GWANGJU = 'GWANGJU',
  DAEJEON = 'DAEJEON',
  ULSAN = 'ULSAN',
  SEJONG = 'SEJONG',
  GYEONGGI = 'GYEONGGI',
  GANGWON = 'GANGWON',
  CHUNGBUK = 'CHUNGBUK',
  CHUNGNAM = 'CHUNGNAM',
  JEONBUK = 'JEONBUK',
  JEONNAM = 'JEONNAM',
  GYEONGBUK = 'GYEONGBUK',
  GYEONGNAM = 'GYEONGNAM',
  JEJU = 'JEJU',
}

export enum GROUP_APPLICATION_STATUS {
  REGISTER = 'REGISTER',
  CANCEL = 'CANCEL',
}

export enum GROUP_STATUS {
  PROGRESS = 'PROGRESS',
  SUCCEED = 'SUCCEED',
  FAIL = 'FAIL',
}

export enum ARTICLE {
  GROUP = 'GROUP',
  FREE = 'FREE',
  QUESTION = 'QUESTION',
  PROJECT = 'PROJECT',
}
