import Head from 'next/head';
import { Button, Slider, createPolymorphicComponent, ButtonProps } from '@mantine/core';
import { IconDatabase } from '@tabler/icons';
import styled from '@emotion/styled';
import { useRouter } from 'next/router';

const _StyledButton = styled(Button)`
  box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
  font-weight: ${({ theme }) => theme.headings.fontWeight};
  color: ${({ theme }) => theme.colors.indigo[8]};
`;

const StyledButton = createPolymorphicComponent<'button', ButtonProps>(_StyledButton);

const StyledSlider = styled(Slider)`
  & .mantine-Slider-bar {
    background-color: pink;
  }

  & .mantine-Slider-thumb {
    border-color: pink;
    background-color: white;
    width: 24px;
    height: 24px;
  }
`;

export default function Home() {
  const router = useRouter();

  const handleClick = () => {
    void router.push('/');
  };

  return (
    <div>
      <Head>
        <title>Create next appp</title>
        <meta name="description" content="Generated by create next appp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StyledButton onClick={handleClick}>Connect to database</StyledButton>
        <div style={{ marginBottom: '10px' }}></div>
        <StyledSlider defaultValue={40} />
        <div style={{ marginBottom: '10px' }}></div>
        <Button leftIcon={<IconDatabase size={14} />}>Connect to database</Button>
      </main>
    </div>
  );
}
