import Head from 'next/head';
import { Button } from '@mantine/core';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create next appp</title>
        <meta name="description" content="Generated by create next appp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button size="md" variant="gradient">
          클릭
        </Button>
      </main>
    </div>
  );
}
