export enum NOTIFICATION_SETTING_TYPE {
  COMMENT = 'COMMENT',
  GROUP = 'GROUP',
}

export enum NOTIFICATION_SETTING_STATUS {
  ON = 'ON',
  OFF = 'OFF',
}

export enum NOTIFICATION_TYPE {
  GROUP_SUCCEED = 'GROUP_SUCCEED',
  GROUP_FAILED = 'GROUP_FAILED',
  COMMENT_ADDED = 'COMMENT_ADDED',
}
